### ISSUE TITLE
Generated Invalid SplashScreen Image Sizes

### ISSUE THREAD

**Issue by xavierlefevre** [bamlab/generator-rn-toolbox#59] opened 2017-02-01 14:56 UTC
Hello guys,

I just `launched yo rn-toolbox:assets --splash backgroundOnboarding.psd --ios`
With a PSD with the right format, and it created a bunch of images that don't seem to have the proper size for x-code : 

![screen shot 2017-02-01 at 15 54 37](https://cloud.githubusercontent.com/assets/14938214/22511749/ee3cec3a-e896-11e6-8a71-36208543aca5.png)

Would you know from where it comes ?

**Comment by Almouro** [comment] 2017-02-01 15:14
Hey, thanks for posting this issue! :)

What are the dimensions of your base image?
Could you send it?

**Comment by xavierlefevre** [comment] 2017-02-01 15:22
My base image dimension : 2208 × 3853

Below

![backgroundonboarding](https://cloud.githubusercontent.com/assets/14938214/22512862/ab82ce88-e89a-11e6-82a8-b997a4fbe1f1.jpg)

**Comment by Almouro** [comment] 2017-02-01 15:30
Ok, the issue is with [these lines](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/imageGenerator.js#L94).
I don't think, the generator can handle non square images

**Comment by yleflour** [comment] 2017-02-09 18:49
Closing as square images are currently required.
Feel free to open a PR to add non-square images compatibility.

**Closed by yleflour** 2017-02-09 18:49 UTC
Labels: bug
