### ISSUE TITLE
Generating splash screen on Android causes crash due to launch_screen_bitmap.xml syntax

### ISSUE THREAD

**Issue by DaveCole** [bamlab/generator-rn-toolbox#111] opened 2017-07-19 17:06 UTC
My apologies for not having the stack trace, I was doing this on my other computer which isn't available at the moment.

Generating splash screens for Android resulted in the app crashing on launch, I was able to fix it by changing the second line in android/app/src/main/res/drawable/launch_screen_bitmap.xml from:

`<item android:drawable="@color/splashBackground"/>`

to the following:

`<item android:drawable="@android:color/darker_gray"/>`

I'm incredibly new to Android development so not sure why or how that fixed things :)

**Comment by Almouro** [comment] 2017-07-20 10:37
Hi @DaveCole, thanks for posting an issue here!

Can you share the content of `android/app/src/main/res/values/colors.xml`?
The generator is supposed to guess the background color of your splash screen and output it there.

**Comment by blaketarter** [comment] 2017-07-25 01:59
I had the same issue.

Here was the stack trace 

```
AndroidRuntime  D  Shutting down VM
E  FATAL EXCEPTION: main
E  Process: com.kcbus, PID: 15020
E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kcbus/com.kcbus.MainActivity}: android.content.res.Resources$NotFoundException:
    Drawable com.kcbus:drawable/launch_screen_bitmap with resource ID #0x7f020054
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
E      at android.app.ActivityThread.-wrap12(ActivityThread.java)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:154)
E      at android.app.ActivityThread.main(ActivityThread.java:6290)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E  Caused by: android.content.res.Resources$NotFoundException: Drawable com.kcbus:drawable/launch_screen_bitmap with resource ID #0x7f020054
E  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_screen_bitmap.xml from drawable resource ID #0x7f020054
E      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
E      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
E      at android.content.res.Resources.getDrawable(Resources.java:771)
E      at android.content.Context.getDrawable(Context.java:526)
E      at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2604)
E      at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2660)
E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:444)
E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:435)
E      at android.app.Activity.setContentView(Activity.java:2464)
E      at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114)
E      at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
E      at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
E      at android.app.Activity.performCreate(Activity.java:6760)
E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
E      at android.app.ActivityThread.-wrap12(ActivityThread.java)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:154)
E      at android.app.ActivityThread.main(ActivityThread.java:6290)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E  Caused by: android.content.res.Resources$NotFoundException: Drawable com.kcbus:color/splashBackground with resource ID #0x7f0c003f
E  Caused by: android.content.res.Resources$NotFoundException: File rgba(0,0,0,0) from drawable resource ID #0x7f0c003f
E      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
E      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
E      at android.content.res.Resources.loadDrawable(Resources.java:858)
E      at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
E      at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:388)
E      at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:267)
E      at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:196)
E      at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
E      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
E      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
E      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
E      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
E      at android.content.res.Resources.getDrawable(Resources.java:771)
E      at android.content.Context.getDrawable(Context.java:526)
E      at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2604)
E      at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2660)
E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:444)
E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:435)
E      at android.app.Activity.setContentView(Activity.java:2464)
E      at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114)
E      at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
E      at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
E      at android.app.Activity.performCreate(Activity.java:6760)
E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
E      at android.app.ActivityThread.-wrap12(ActivityThread.java)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:154)
E      at android.app.ActivityThread.main(ActivityThread.java:6290)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E  Caused by: java.io.FileNotFoundException: rgba(0,0,0,0)
E      at android.content.res.AssetManager.openNonAssetNative(Native Method)
E      at android.content.res.AssetManager.openNonAsset(AssetManager.java:451)
E      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:718)
E      ... 33 more
AppTracker  D  App Event: crash
```

I was able to fix it by changing colors.xml from
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <item name="splashBackground" type="color">rgba(0,0,0,0)</item> 
</resources>

```
to
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <item name="splashBackground" type="color">#4285f4</item> 
</resources>

```

**Comment by Almouro** [comment] 2017-07-25 18:28
Hi @blaketarter, thanks for your stack trace!
Can you also add the image you were trying to use, and the command you ran?

Thanks! :)

**Comment by blaketarter** [comment] 2017-07-26 15:53
@Almouro here you go

`yo rn-toolbox:assets --splash ~/Design/kcbus/splash.psd --android`

![splash](https://user-images.githubusercontent.com/6101761/28630633-623cdf04-71f0-11e7-8ccc-11c305316be6.png)

the file was a psd (but I can't upload that file type here) so here is the png version.

**Comment by philolo1** [comment] 2017-11-16 16:08
Some issue here

**Comment by philolo1** [comment] 2017-11-16 16:13
What you want to do is  <item name="splashBackground" type="color">#FF000000</item> , this means full transparency

**Comment by philolo1** [comment] 2017-11-16 16:20
@Almouro the issue seems, that in _setupAndroidSplashScreen, if we get a transparent pixel, getPixelColor returns an string like "rgb(0, 0, 0, 0) ", but android only accepts somethink like that #FF000000, where the first two characters are the transcparencies. 
One easy fix would be to convert them back to a string, but that is kind of ugly.

**Comment by Kida007** [comment] 2017-11-18 14:55
when I Changed splash.psd to splash.png it Worked Fine.

**Comment by Kida007** [comment] 2017-11-18 15:02
it is still crashing when we use PSD file. when I accidentally used a png file it didn't crashed but was fixed there all the time .

**Comment by Almouro** [comment] 2017-11-21 18:28
Hi @blaketarter @philolo1, the command seems to be failing for some `psd` but I cannot reproduce it. 

Since @blaketarter mentioned you can't upload `psd` on Github, could one of you share your psd via another service like WeTransfer, for example?

But for now, the best solution is to convert it into a `png` and then run the command on the `png`

**Comment by seangransee** [comment] 2017-12-23 04:22
I was having the same issue (generated my splash screen from a .psd). @blaketarter's solution of modifying the `colors.xml` file fixed it for me.

**Comment by uppercase-army** [comment] 2018-01-02 14:46
Same issue, I was using a PNG.

**Comment by roysG** [comment] 2018-06-08 03:27
@seangransee, what color should i use for transparent?
Can you share your colors.xml?

Thanks.

**Comment by seangransee** [comment] 2018-06-08 14:14
My colors.xml just specifies a background color, so having a transparent color isn't relevant. I used brown as my background color.

Here's what my colors.xml file looks like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">#260B01</item>
</resources>
```

**Comment by sagarrabadiya** [comment] 2018-07-23 16:56
same issue here, i have to manually change colors.xml file when trigger build, as i am trying to make build process automated using android flavours build gets stopped once run on android and checking logcat shows this exact same error regarding launch_screen_bitmap not found

**Comment by joh-klein** [comment] 2018-08-14 12:37
Probably fixed with #185

**Comment by antonioabb** [comment] 2019-01-23 10:49
Same issue. I changed manually colors.xml. 
Value of **item** was empty, only with a '**#**' character. I changed by #000 then app runs again.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">#</item>
</resources>
```

**Comment by tobbbe** [comment] 2019-03-28 10:32
same issue. app doesnt start and logcat shows:

```android.content.res.Resources$NotFoundException: File #FFFFFFFFFFFFFFFFFFFF```

My colors.xml was this.
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item name="splashBackground" type="color">#FFFFFFFFFFFFFFFFFFFF</item>
</resources>
```

Works when I change `#FFFFFFFFFFFFFFFFFFFF` to `#fff`.

Changing it to `rgb(0,0,0)` as (docs says)[https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md#android-1] causes same error.

Was using psd-file to generate

**Comment by joh-klein** [comment] 2019-03-28 10:40
I had the same issues with psd files. And after too many hours gave up and switched to bitmap files (png in my case)

**Comment by vipul1298** [comment] 2019-05-10 11:48
but it doesn't work for me by changing into color.xml

**Comment by kelalaka153** [comment] 2019-07-08 11:16
Another solution is using a shape as in [here](https://stackoverflow.com/a/40845366/1820553). This was the easiest solution for me.

**Comment by yleflour** [comment] 2019-09-05 14:27
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version uses creates a whole layout for the splash-screen making it easier to customize it, regarding the color issue, we don't compute it by default anymore but let you input yours. Hope it helps you with your issue 😉

**Closed by yleflour** 2019-09-05 14:27 UTC
Labels: Assets, bug
