### ISSUE TITLE
splash screen size issue in android

### ISSUE THREAD

**Issue by imadarif** [bamlab/generator-rn-toolbox#187] opened 2018-07-04 15:27 UTC
i prepare a splash.png file with 2732*2732. i run the command to generate splash screen for both ios and android. for ios is perfect but for android its showing color on background image was not fit properly

**Comment by bintoll** [comment] 2018-07-30 04:32
+1 the same

**Comment by Juliocbr** [comment] 2018-08-07 19:06
+1 the same

**Comment by joh-klein** [comment] 2018-08-14 13:36
duplicate of #172 ?

**Comment by russ666** [comment] 2018-10-09 06:51
found the solution: replace in `./android/app/src/main/res/drawable/launch_screen_bitmap.xml` value of `android:gravity` from `center` to `fill`

**Comment by airled** [comment] 2019-07-03 17:44
@russ666 It fills, yes, but it resizes image incorrectly if display and image have different ratio

**Comment by yleflour** [comment] 2019-09-05 14:20
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version handles 3 different types of rendering for the splashscreen image (center, contain and cover), so it should solve your issue 😉

**Closed by yleflour** 2019-09-05 14:20 UTC
